env:
  global:
  - COVERITY_SCAN_TOKEN=G_KYq49p4CiHkumRjFOrRw
dist: trusty
sudo: false
language: csharp
solution: WowPacketParser.sln
matrix:
  include:
  - dotnet: 1.0.1
    mono: none
    env: DOTNETCORE=1
  - mono: latest
  allow_failures:
  - dotnet: 1.0.1
install: ./scripts/travis-install.sh
script: ./scripts/travis-build.sh
addons:
  coverity_scan:
    project:
      name: TrinityCore/WowPacketParser
      version: 1.0
      description: WPP
    notification_email: dnpd.dd@gmail.com
    build_command_prepend: 
    build_command: xbuild /p:TargetFrameworkVersion="v4.6"
    branch_pattern: master
